name: YouTube to Port (Simple)

on:
  workflow_dispatch:

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch videos from YouTube
        run: |
          curl -s "https://www.googleapis.com/youtube/v3/playlistItems?part=snippet&maxResults=5&playlistId=PLJkDlUAxVFug_IN4Cf_eC6SQfzVNXeAms&key=${{ secrets.YOUTUBE_API_KEY }}" > videos.json
      - name: Send to Port
        run: |
          cat videos.json | jq -c '.items[] | {
            identifier: (.snippet.resourceId.videoId // .id),
            video_url: "https://www.youtube.com/watch?v=\(.snippet.resourceId.videoId // .id)"
          }' | while read -r video; do
      
            echo "payload: $video"
      
            curl -X POST "https://api.getport.io/v1/blueprints/videos/entities?upsert=true" \
              -H "Authorization: Bearer ${{ secrets.PORT_API_KEY }}" \
              -H "Content-Type: application/json" \
              -d "$video"
      
          done
